; Generated by Stone Compiler (LLVM backend)
; Do not edit - regenerate from Stone source

target triple = "x86_64-pc-windows-msvc"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

; Stone runtime type definitions
%String = type { i64, ptr }                    ; { len, data }
%Array = type { i64, ptr }                     ; { len, data (double*) }
%Array2D = type { i64, i64, ptr }              ; { rows, cols, data (double*) }
%Record = type { i64, ptr, ptr }               ; { count, keys (i8**), values (double*) }
%Closure = type { ptr, ptr }                   ; { funcptr, env }

; String constants
@.str.0 = private unnamed_addr constant [8 x i8] c"Hello, \00"
@.str.1 = private unnamed_addr constant [20 x i8] c"! Welcome to Stone.\00"
@.str.2 = private unnamed_addr constant [6 x i8] c"World\00"
@.str.3 = private unnamed_addr constant [11 x i8] c"Stone User\00"
@.str.4 = private unnamed_addr constant [6 x i8] c"Alice\00"
@.str.5 = private unnamed_addr constant [4 x i8] c"Bob\00"
@.str.6 = private unnamed_addr constant [8 x i8] c"Charlie\00"

; Runtime and intrinsic declarations
declare ptr @stone_array_new(i64)
declare double @stone_array_get(ptr, i64)
declare ptr @stone_push_ptr(ptr, ptr)
declare void @stone_print(double)
declare void @stone_print_ptr(ptr)
declare void @stone_array_set_ptr(ptr, i64, ptr)
declare ptr @stone_array_get_ptr(ptr, i64)
declare void @stone_runtime_init()
declare void @stone_runtime_shutdown()
declare void @stone_timer_start()
declare void @stone_timer_stop()

; Module globals
@names = internal global ptr null, align 8
@greetings = internal global ptr null, align 8

define ptr @greetc1(double %name) nounwind {
entry:
  %name.addr = alloca double, align 8
  store double %name, ptr %name.addr, align 8
  br label %fn_entry

fn_entry:
  %str_conv_0 = call ptr @stone_to_str(double %name)
  %v13 = call ptr @stone_string_concat(ptr @.str.0, ptr %str_conv_0)
  %v17 = call ptr @stone_string_concat(ptr %v13, ptr @.str.1)
  ret ptr %v17
}

define ptr @greet_allc1(ptr noalias nocapture readonly %names) nounwind {
entry:
  %greetings.addr = alloca ptr, align 8
  store ptr null, ptr %greetings.addr, align 8
  %idx38.addr = alloca i64, align 8
  store i64 0, ptr %idx38.addr, align 8
  %i.addr = alloca i64, align 8
  store i64 0, ptr %i.addr, align 8
  %names.addr = alloca ptr, align 8
  store ptr %names, ptr %names.addr, align 8
  br label %fn_entry

fn_entry:
  %t0 = getelementptr { i64, i64, ptr }, ptr %names, i32 0, i32 0
  %len33 = load i64, ptr %t0
  %arr35 = call ptr @stone_array_new(i64 0)
  store ptr %arr35, ptr %greetings.addr, align 8
  store i64 0, ptr %idx38.addr, align 8
  store i64 0, ptr %i.addr, align 8
  br label %idx_header_3, !llvm.loop !0

idx_header_3:
  %t1 = load i64, ptr %idx38.addr, align 8
  %cond41 = icmp slt i64 %t1, %len33
  br i1 %cond41, label %idx_body_4, label %idx_exit_5

idx_body_4:
  %t2 = load i64, ptr %idx38.addr, align 8
  store i64 %t2, ptr %i.addr, align 8
  %t3 = load i64, ptr %i.addr, align 8
  %elem44 = call double @stone_array_get(ptr %names, i64 %t3)
  %call46 = call ptr @greetc1(double %elem44)
  %t4 = load ptr, ptr %greetings.addr, align 8
  %pushed48 = call ptr @stone_push_ptr(ptr %t4, ptr %call46)
  store ptr %pushed48, ptr %greetings.addr, align 8
  %next51 = add nsw i64 %t2, 1
  store i64 %next51, ptr %idx38.addr, align 8
  br label %idx_header_3, !llvm.loop !1

idx_exit_5:
  %t5 = load ptr, ptr %greetings.addr, align 8
  ret ptr %t5
}

define i32 @main() {
entry:
  call void @stone_runtime_init()
  call void @stone_timer_start()
  %iter_arr25.addr = alloca ptr, align 8
  store ptr null, ptr %iter_arr25.addr, align 8
  %iter_idx29.addr = alloca i64, align 8
  store i64 0, ptr %iter_idx29.addr, align 8
  %g.addr = alloca ptr, align 8
  store ptr null, ptr %g.addr, align 8
  %c1 = bitcast ptr @.str.2 to ptr
  %call3 = call ptr @greetc1(ptr @.str.2)
  call void @stone_print_ptr(ptr %call3)
  %c7 = bitcast ptr @.str.3 to ptr
  %call9 = call ptr @greetc1(ptr @.str.3)
  call void @stone_print_ptr(ptr %call9)
  %c13 = bitcast ptr @.str.4 to ptr
  %c15 = bitcast ptr @.str.5 to ptr
  %c17 = bitcast ptr @.str.6 to ptr
  %arr19 = call ptr @stone_array_new(i64 3)
  call void @stone_array_set_ptr(ptr %arr19, i64 0, ptr @.str.4)
  call void @stone_array_set_ptr(ptr %arr19, i64 1, ptr @.str.5)
  call void @stone_array_set_ptr(ptr %arr19, i64 2, ptr @.str.6)
  store ptr %arr19, ptr @names, align 8
  %t0 = load ptr, ptr @names, align 8
  %call22 = call ptr @greet_allc1(ptr %t0)
  store ptr %call22, ptr @greetings, align 8
  %t1 = load ptr, ptr @greetings, align 8
  store ptr %t1, ptr %iter_arr25.addr, align 8
  %t2 = load ptr, ptr %iter_arr25.addr, align 8
  %t3 = getelementptr { i64, i64, ptr }, ptr %t2, i32 0, i32 0
  %iter_len27 = load i64, ptr %t3
  store i64 0, ptr %iter_idx29.addr, align 8
  br label %loop_header_0

loop_header_0:
  %t4 = load i64, ptr %iter_idx29.addr, align 8
  %cond31 = icmp slt i64 %t4, %iter_len27
  br i1 %cond31, label %loop_body_1, label %loop_exit_2

loop_body_1:
  %t5 = load ptr, ptr %iter_arr25.addr, align 8
  %t6 = load i64, ptr %iter_idx29.addr, align 8
  %iter_elem33 = call ptr @stone_array_get_ptr(ptr %t5, i64 %t6)
  store ptr %iter_elem33, ptr %g.addr, align 8
  %t7 = load ptr, ptr %g.addr, align 8
  call void @stone_print_ptr(ptr %t7)
  %next_idx38 = add nsw i64 %t6, 1
  store i64 %next_idx38, ptr %iter_idx29.addr, align 8
  br label %loop_header_0

loop_exit_2:
  call void @stone_timer_stop()
  call void @stone_runtime_shutdown()
  ret i32 0
}

; Loop vectorization metadata
!0 = distinct !{!0, !2, !3}
!2 = !{!"llvm.loop.vectorize.enable", i1 true}
!3 = !{!"llvm.loop.vectorize.width", i32 4}
!1 = distinct !{!1, !4, !5}
!4 = !{!"llvm.loop.vectorize.enable", i1 true}
!5 = !{!"llvm.loop.vectorize.width", i32 4}